"""Structured accident case seeds for demo and RAG corpus (Task 3-C.8 / 4-B.1)."""

from __future__ import annotations

from typing import Any

from sqlalchemy.orm import Session

from app.infrastructure.database.models import AccidentCaseLibrary
from app.services.cases.milvus_reingest import trigger_accident_case_milvus_reingest
from app.services.cases.seed_cases_extended import ACCIDENT_CASE_SEEDS_EXTENDED
from app.services.cases.seed_cases_l3_bulk import ACCIDENT_CASE_SEEDS_L3_BULK

ACCIDENT_CASE_SEEDS: list[dict] = [
    {
        "accident_case_id": "AC-MVP-001",
        "tenant_id": "CSCEC",
        "accident_type": "高处坠落",
        "severity": "一般事故",
        "project_type": "housing",
        "operation_scene": "主体结构临边作业",
        "direct_cause": "临边防护缺失，作业人员未正确使用安全带。",
        "indirect_cause": "班前交底不到位，现场巡检未及时发现防护缺口。",
        "involved_subjects": {"subjects": ["project", "subcontractor", "worker"]},
        "warning_indicators": [
            {"metric_code": "HAZARD_OVERDUE_COUNT", "value": 2},
            {"metric_code": "WORKER_VIOLATION_30D", "value": 1},
        ],
        "rectification_measures": "恢复临边防护，复核高处作业交底，整改完成后复查闭环。",
        "tags": ["高处作业", "临边防护", "班前教育"],
    },
    {
        "accident_case_id": "AC-MVP-002",
        "tenant_id": "CSCEC",
        "accident_type": "物体打击",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "塔吊吊装作业",
        "direct_cause": "吊装半径内警戒隔离不足，零散材料绑扎不牢。",
        "indirect_cause": "起重吊装旁站不到位，交叉作业协调不足。",
        "involved_subjects": {"subjects": ["equipment", "subcontractor"]},
        "warning_indicators": [
            {"metric_code": "CROSS_OPERATION_COUNT", "value": 3},
            {"metric_code": "EQUIPMENT_INSPECTION_OVERDUE", "value": 0},
        ],
        "rectification_measures": "设置吊装警戒区，复核吊具和绑扎，安排专人旁站。",
        "tags": ["吊装", "交叉作业", "物体打击"],
    },
    {
        "accident_case_id": "AC-MVP-003",
        "tenant_id": "CSCEC",
        "accident_type": "触电",
        "severity": "近失",
        "project_type": "infrastructure",
        "operation_scene": "临时用电检修",
        "direct_cause": "配电箱接地保护失效，检修前未验电。",
        "indirect_cause": "临电巡检记录不完整，电工复核机制不足。",
        "involved_subjects": {"subjects": ["worker", "equipment"]},
        "warning_indicators": [
            {"metric_code": "TEMP_ELECTRICITY_HAZARD_COUNT", "value": 1},
            {"metric_code": "SPECIAL_CERT_EXPIRED_COUNT", "value": 0},
        ],
        "rectification_measures": "更换漏保并测试接地，执行停送电挂牌和验电流程。",
        "tags": ["临时用电", "触电", "特种作业"],
    },
    {
        "accident_case_id": "AC-MVP-004",
        "tenant_id": "CSCEC",
        "accident_type": "机械伤害",
        "severity": "一般事故",
        "project_type": "infrastructure",
        "operation_scene": "钢筋加工区作业",
        "direct_cause": "钢筋加工设备防护罩缺失，操作人员手部进入危险区域。",
        "indirect_cause": "设备点检流于形式，作业区安全隔离不足。",
        "involved_subjects": {"subjects": ["worker", "equipment", "subcontractor"]},
        "warning_indicators": [
            {"metric_code": "EQUIPMENT_ABNORMAL_COUNT", "value": 1},
            {"metric_code": "WORKER_TRAINING_PASS_RATE", "value": 0.82},
        ],
        "rectification_measures": "恢复设备防护罩，重做设备点检，组织机械伤害专项培训。",
        "tags": ["机械伤害", "设备点检", "加工区"],
    },
    {
        "accident_case_id": "AC-MVP-005",
        "tenant_id": "CSCEC",
        "accident_type": "坍塌",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "深基坑支护",
        "direct_cause": "连续降雨后基坑边坡局部开裂，支护监测预警处置滞后。",
        "indirect_cause": "雨季专项检查频次不足，监测数据未及时联动工单。",
        "involved_subjects": {"subjects": ["project", "subcontractor"]},
        "warning_indicators": [
            {"metric_code": "MAJOR_HAZARD_OVERDUE_COUNT", "value": 1},
            {"metric_code": "WEATHER_RISK_LEVEL", "value": "high"},
        ],
        "rectification_measures": "加密监测，卸载坡顶堆载，补强支护并升级重大隐患工单。",
        "tags": ["基坑", "雨季施工", "重大隐患"],
    },
    {
        "accident_case_id": "AC-MVP-006",
        "tenant_id": "CSCEC",
        "accident_type": "火灾",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "保温材料堆放区",
        "direct_cause": "易燃保温材料靠近动火点，监护人员离岗。",
        "indirect_cause": "动火审批不严，可燃物清理不彻底。",
        "involved_subjects": {"subjects": ["project", "subcontractor"]},
        "warning_indicators": [{"metric_code": "HOT_WORK_PERMIT_COUNT", "value": 2}],
        "rectification_measures": "清理可燃物，恢复动火监护，补充消防器材并复盘动火票。",
        "tags": ["动火作业", "火灾", "可燃物管理"],
    },
    {
        "accident_case_id": "AC-MVP-007",
        "tenant_id": "CSCEC",
        "accident_type": "中毒窒息",
        "severity": "一般事故",
        "project_type": "municipal",
        "operation_scene": "地下管廊有限空间",
        "direct_cause": "未检测气体浓度即进入有限空间作业。",
        "indirect_cause": "有限空间作业票未执行，救援器材未到位。",
        "involved_subjects": {"subjects": ["worker", "subcontractor"]},
        "warning_indicators": [{"metric_code": "CONFINED_SPACE_PERMIT_COUNT", "value": 0}],
        "rectification_measures": "停工复盘有限空间程序，配备气体检测和救援三脚架。",
        "tags": ["有限空间", "中毒窒息", "作业票"],
    },
    {
        "accident_case_id": "AC-MVP-008",
        "tenant_id": "CSCEC",
        "accident_type": "车辆伤害",
        "severity": "近失",
        "project_type": "infrastructure",
        "operation_scene": "施工便道交叉路口",
        "direct_cause": "渣土车转弯未鸣笛，行人未走人行通道。",
        "indirect_cause": "场内交通组织混乱，限速标识缺失。",
        "involved_subjects": {"subjects": ["worker", "equipment"]},
        "warning_indicators": [{"metric_code": "SITE_TRAFFIC_VIOLATION_COUNT", "value": 3}],
        "rectification_measures": "重新划定人车分流路线，设置限速和反光标识。",
        "tags": ["场内交通", "车辆伤害", "便道管理"],
    },
    {
        "accident_case_id": "AC-MVP-009",
        "tenant_id": "CSCEC",
        "accident_type": "灼烫",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "屋面防水热熔施工",
        "direct_cause": "热熔枪操作不当，熔融材料溅落烫伤附近人员。",
        "indirect_cause": "交叉作业未隔离，防护用品佩戴不规范。",
        "involved_subjects": {"subjects": ["worker"]},
        "warning_indicators": [{"metric_code": "PPE_COMPLIANCE_RATE", "value": 0.78}],
        "rectification_measures": "设置热作业警戒区，强制佩戴防烫手套和护目镜。",
        "tags": ["热熔防水", "灼烫", "PPE"],
    },
    {
        "accident_case_id": "AC-MVP-010",
        "tenant_id": "CSCEC",
        "accident_type": "淹溺",
        "severity": "近失",
        "project_type": "municipal",
        "operation_scene": "河道清淤围堰",
        "direct_cause": "围堰局部渗漏，作业人员撤离不及时。",
        "indirect_cause": "汛期预案演练不足，值班巡查频次不够。",
        "involved_subjects": {"subjects": ["project", "worker"]},
        "warning_indicators": [{"metric_code": "WEATHER_RISK_LEVEL", "value": "high"}],
        "rectification_measures": "加固围堰并完善汛期撤离路线和应急演练。",
        "tags": ["围堰", "汛期施工", "淹溺"],
    },
    {
        "accident_case_id": "AC-MVP-011",
        "tenant_id": "CSCEC",
        "accident_type": "起重伤害",
        "severity": "一般事故",
        "project_type": "housing",
        "operation_scene": "施工升降机安装",
        "direct_cause": "标准节螺栓预紧力不足，试运行中连接松动。",
        "indirect_cause": "安装验收记录造假，监理旁站缺失。",
        "involved_subjects": {"subjects": ["equipment", "subcontractor"]},
        "warning_indicators": [{"metric_code": "EQUIPMENT_INSPECTION_OVERDUE", "value": 1}],
        "rectification_measures": "重新扭矩复核标准节螺栓，组织第三方复检后复工。",
        "tags": ["施工升降机", "起重伤害", "安装验收"],
    },
    {
        "accident_case_id": "AC-MVP-012",
        "tenant_id": "CSCEC",
        "accident_type": "模板支撑失稳",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "高大模板浇筑",
        "direct_cause": "扫地杆和剪刀撑缺失，混凝土浇筑荷载超设计。",
        "indirect_cause": "专项方案未按图施工，验收签字流于形式。",
        "involved_subjects": {"subjects": ["project", "subcontractor"]},
        "warning_indicators": [{"metric_code": "FORMWORK_HAZARD_COUNT", "value": 2}],
        "rectification_measures": "暂停浇筑，按方案补设杆件并重新组织专家验收。",
        "tags": ["高大模板", "支撑失稳", "专项方案"],
    },
    {
        "accident_case_id": "AC-MVP-013",
        "tenant_id": "CSCEC",
        "accident_type": "脚手架倒塌",
        "severity": "一般事故",
        "project_type": "housing",
        "operation_scene": "外墙装修脚手架",
        "direct_cause": "连墙件拆除过多，架体失稳整体倾倒。",
        "indirect_cause": "抢工期违规拆改架体，日常巡查未制止。",
        "involved_subjects": {"subjects": ["worker", "subcontractor"]},
        "warning_indicators": [{"metric_code": "SCAFFOLD_INSPECTION_OVERDUE", "value": 1}],
        "rectification_measures": "全面停工整顿脚手架，恢复连墙件并重新验收挂牌。",
        "tags": ["脚手架", "连墙件", "倒塌"],
    },
    {
        "accident_case_id": "AC-MVP-014",
        "tenant_id": "CSCEC",
        "accident_type": "塔吊倾覆",
        "severity": "险情",
        "project_type": "infrastructure",
        "operation_scene": "桥梁预制梁吊装",
        "direct_cause": "超力矩吊装，地基沉降导致轨道不平。",
        "indirect_cause": "轨道基础验收资料不完整，司机违章冒险作业。",
        "involved_subjects": {"subjects": ["equipment", "project"]},
        "warning_indicators": [{"metric_code": "CRANE_OVERLOAD_ALARM_COUNT", "value": 1}],
        "rectification_measures": "校正轨道基础，恢复力矩限制器并开展司机再培训。",
        "tags": ["塔吊", "超力矩", "轨道基础"],
    },
    {
        "accident_case_id": "AC-MVP-015",
        "tenant_id": "CSCEC",
        "accident_type": "高处落物",
        "severity": "近失",
        "project_type": "housing",
        "operation_scene": "装饰装修交叉楼层",
        "direct_cause": "上层作业工具未系防坠绳，物料滑落。",
        "indirect_cause": "垂直交叉作业未错时，下层防护棚不足。",
        "involved_subjects": {"subjects": ["worker", "subcontractor"]},
        "warning_indicators": [{"metric_code": "CROSS_OPERATION_COUNT", "value": 4}],
        "rectification_measures": "落实工具防坠和错时交叉作业，增设防护棚。",
        "tags": ["交叉作业", "高处落物", "防坠"],
    },
    {
        "accident_case_id": "AC-MVP-016",
        "tenant_id": "CSCEC",
        "accident_type": "地下管线破损",
        "severity": "险情",
        "project_type": "municipal",
        "operation_scene": "道路开挖施工",
        "direct_cause": "机械开挖未探明燃气管线位置，造成破损泄漏。",
        "indirect_cause": "管线交底图纸更新滞后，监护人员未到场。",
        "involved_subjects": {"subjects": ["project", "equipment"]},
        "warning_indicators": [{"metric_code": "UTILITY_DAMAGE_RISK", "value": "high"}],
        "rectification_measures": "停工配合燃气公司抢修，更新管线图纸并人工探沟复核。",
        "tags": ["管线保护", "开挖", "燃气"],
    },
    {
        "accident_case_id": "AC-MVP-017",
        "tenant_id": "CSCEC",
        "accident_type": "冬季施工滑坠",
        "severity": "近失",
        "project_type": "infrastructure",
        "operation_scene": "钢结构屋面檩条安装",
        "direct_cause": "屋面结冰未除冰，作业人员滑倒接近檐口。",
        "indirect_cause": "冬季施工防滑措施未落实，气象预警未传导到班组。",
        "involved_subjects": {"subjects": ["worker"]},
        "warning_indicators": [{"metric_code": "WEATHER_RISK_LEVEL", "value": "medium"}],
        "rectification_measures": "除冰防滑，暂停高处作业并发布低温施工控制措施。",
        "tags": ["冬季施工", "防滑", "高处作业"],
    },
    {
        "accident_case_id": "AC-MVP-018",
        "tenant_id": "CSCEC",
        "accident_type": "夜间施工",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "夜间混凝土浇筑",
        "direct_cause": "照明不足导致人员误入泵车回转半径。",
        "indirect_cause": "夜间施工方案审批不严，照明和警戒不到位。",
        "involved_subjects": {"subjects": ["worker", "equipment"]},
        "warning_indicators": [{"metric_code": "NIGHT_WORK_PERMIT_COUNT", "value": 1}],
        "rectification_measures": "补齐作业面照明和警戒设施，修订夜间施工方案。",
        "tags": ["夜间施工", "照明", "泵车作业"],
    },
    {
        "accident_case_id": "AC-MVP-019",
        "tenant_id": "CSCEC",
        "accident_type": "分包管理失控",
        "severity": "一般事故",
        "project_type": "housing",
        "operation_scene": "多分包交叉区域",
        "direct_cause": "分包队伍未培训即进场，违章操作引发险情升级。",
        "indirect_cause": "分包准入审核不严，总包统一协调机制失效。",
        "involved_subjects": {"subjects": ["subcontractor", "project"]},
        "warning_indicators": [{"metric_code": "SUBCONTRACTOR_VIOLATION_30D", "value": 5}],
        "rectification_measures": "清退违规班组，重建分包准入和安全协调例会机制。",
        "tags": ["分包管理", "准入审核", "协调机制"],
    },
    {
        "accident_case_id": "AC-MVP-020",
        "tenant_id": "CSCEC",
        "accident_type": "文明施工",
        "severity": "险情",
        "project_type": "municipal",
        "operation_scene": "临街围挡外侧",
        "direct_cause": "围挡基础松动倾倒，砸中市政人行道设施。",
        "indirect_cause": "日常巡检未发现围挡沉降，极端天气应对不足。",
        "involved_subjects": {"subjects": ["project"]},
        "warning_indicators": [{"metric_code": "SITE_ENCROACHMENT_RISK", "value": 1}],
        "rectification_measures": "加固围挡基础并增设防风拉结，完善市政协调通报。",
        "tags": ["文明施工", "围挡", "市政协调"],
    },
    *ACCIDENT_CASE_SEEDS_EXTENDED,
    *ACCIDENT_CASE_SEEDS_L3_BULK,
]

CORE_ACCIDENT_TYPES: tuple[str, ...] = (
    "高处坠落",
    "物体打击",
    "触电",
    "机械伤害",
    "起重伤害",
    "坍塌",
)


def seed_accident_cases(db: Session, *, reingest_milvus: bool = False) -> dict[str, Any] | None:
    for payload in ACCIDENT_CASE_SEEDS:
        row = db.query(AccidentCaseLibrary).filter(
            AccidentCaseLibrary.accident_case_id == payload["accident_case_id"]
        ).first()
        if row is None:
            row = AccidentCaseLibrary(
                accident_case_id=payload["accident_case_id"],
                tenant_id=payload["tenant_id"],
            )
            db.add(row)
        for field, value in payload.items():
            setattr(row, field, value)
        row.status = "active"
        row.embedding_version = None
    db.commit()
    if not reingest_milvus:
        return None
    return trigger_accident_case_milvus_reingest(db, tenant_id="CSCEC")
