"""Phase 4-B.1 extended accident case seeds (AC-MVP-021 .. 050)."""

from __future__ import annotations

ACCIDENT_CASE_SEEDS_EXTENDED: list[dict] = [
    {
        "accident_case_id": "AC-MVP-021",
        "tenant_id": "CSCEC",
        "accident_type": "高处坠落",
        "severity": "一般事故",
        "project_type": "mep",
        "operation_scene": "机电管廊支架安装",
        "direct_cause": "管廊支架临时作业平台护栏缺失，作业人员失足坠落。",
        "indirect_cause": "高处作业票审批不严，安全绳双钩未落实。",
        "involved_subjects": {"subjects": ["worker", "subcontractor"]},
        "warning_indicators": [{"metric_code": "WORKER_SPECIAL_CERT_EXPIRED", "value": 1}],
        "rectification_measures": "补设作业平台护栏，复核双钩安全带使用并停工教育。",
        "tags": ["高处坠落", "机电安装", "安全带"],
    },
    {
        "accident_case_id": "AC-MVP-022",
        "tenant_id": "CSCEC",
        "accident_type": "高处坠落",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "铝合金窗安装",
        "direct_cause": "吊篮安全锁失效，作业人员接近坠落边缘被拦阻。",
        "indirect_cause": "吊篮日常检查记录造假，复检周期超期。",
        "involved_subjects": {"subjects": ["worker", "equipment"]},
        "warning_indicators": [{"metric_code": "EQUIPMENT_INSPECTION_OVERDUE", "value": 1}],
        "rectification_measures": "停用吊篮并第三方复检，恢复安全锁后重新验收。",
        "tags": ["高处坠落", "吊篮", "设备检验"],
    },
    {
        "accident_case_id": "AC-MVP-023",
        "tenant_id": "CSCEC",
        "accident_type": "高处坠落",
        "severity": "近失",
        "project_type": "infrastructure",
        "operation_scene": "桥梁墩柱模板拆除",
        "direct_cause": "拆除顺序错误导致作业面失稳，人员滑落被安全带拉住。",
        "indirect_cause": "专项拆除方案未交底，监护人员未在岗。",
        "involved_subjects": {"subjects": ["worker", "project"]},
        "warning_indicators": [{"metric_code": "HAZARD_OVERDUE_COUNT", "value": 1}],
        "rectification_measures": "按方案重组拆除工序，设置专职高处作业监护人。",
        "tags": ["高处坠落", "模板拆除", "专项方案"],
    },
    {
        "accident_case_id": "AC-MVP-024",
        "tenant_id": "CSCEC",
        "accident_type": "物体打击",
        "severity": "一般事故",
        "project_type": "municipal",
        "operation_scene": "综合管廊顶板预留孔",
        "direct_cause": "顶板预留孔未覆盖，小型工具坠落砸伤下方巡检人员。",
        "indirect_cause": "孔洞防护标准化不到位，上下层未错时作业。",
        "involved_subjects": {"subjects": ["worker"]},
        "warning_indicators": [{"metric_code": "OPENING_UNCOVERED_COUNT", "value": 2}],
        "rectification_measures": "全覆盖预留孔并设置硬质防护，实行错时上下交叉作业。",
        "tags": ["物体打击", "孔洞防护", "市政管廊"],
    },
    {
        "accident_case_id": "AC-MVP-025",
        "tenant_id": "CSCEC",
        "accident_type": "物体打击",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "装配式建筑构件吊装",
        "direct_cause": "构件吊装钢丝绳断丝，构件摆动撞击脚手架。",
        "indirect_cause": "吊索具检查流于形式，吊装警戒区设置不足。",
        "involved_subjects": {"subjects": ["equipment", "subcontractor"]},
        "warning_indicators": [{"metric_code": "RIGGING_INSPECTION_OVERDUE", "value": 1}],
        "rectification_measures": "更换吊索具并建立使用前检查清单，扩大警戒范围。",
        "tags": ["物体打击", "装配式", "吊索具"],
    },
    {
        "accident_case_id": "AC-MVP-026",
        "tenant_id": "CSCEC",
        "accident_type": "物体打击",
        "severity": "近失",
        "project_type": "infrastructure",
        "operation_scene": "隧道通风管道安装",
        "direct_cause": "风管法兰螺栓松动，吊装段滑落被下方挡板挡住。",
        "indirect_cause": "螺栓扭矩未复核，安装质量验收不严。",
        "involved_subjects": {"subjects": ["worker", "subcontractor"]},
        "warning_indicators": [{"metric_code": "INSTALLATION_DEFECT_COUNT", "value": 1}],
        "rectification_measures": "全面复核法兰连接扭矩，增设防坠钢丝绳。",
        "tags": ["物体打击", "隧道机电", "安装质量"],
    },
    {
        "accident_case_id": "AC-MVP-027",
        "tenant_id": "CSCEC",
        "accident_type": "触电",
        "severity": "一般事故",
        "project_type": "mep",
        "operation_scene": "配电室设备调试",
        "direct_cause": "带电调试时绝缘手套破损，操作人员触电。",
        "indirect_cause": "绝缘防护用品检查缺失，停送电程序执行不到位。",
        "involved_subjects": {"subjects": ["worker", "equipment"]},
        "warning_indicators": [{"metric_code": "PPE_INSPECTION_OVERDUE", "value": 1}],
        "rectification_measures": "更换绝缘防护用品，严格执行停送电和验电挂牌。",
        "tags": ["触电", "机电调试", "停送电"],
    },
    {
        "accident_case_id": "AC-MVP-028",
        "tenant_id": "CSCEC",
        "accident_type": "触电",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "桩基施工电焊作业",
        "direct_cause": "电焊机二次侧接线裸露，雨天作业导致漏电告警。",
        "indirect_cause": "雨天施工审批不严，临电巡检未覆盖桩基区域。",
        "involved_subjects": {"subjects": ["worker", "equipment"]},
        "warning_indicators": [{"metric_code": "WEATHER_RISK_LEVEL", "value": "high"}],
        "rectification_measures": "雨天停止电焊作业，整改临电线路并加装漏电保护。",
        "tags": ["触电", "电焊作业", "雨季施工"],
    },
    {
        "accident_case_id": "AC-MVP-029",
        "tenant_id": "CSCEC",
        "accident_type": "触电",
        "severity": "近失",
        "project_type": "municipal",
        "operation_scene": "路灯电缆敷设",
        "direct_cause": "机械开挖接近高压电缆警示桩，电缆外皮磨损放电。",
        "indirect_cause": "地下管线图纸与现场不符，人工探沟未执行。",
        "involved_subjects": {"subjects": ["equipment", "project"]},
        "warning_indicators": [{"metric_code": "UTILITY_DAMAGE_RISK", "value": "high"}],
        "rectification_measures": "人工探明电缆位置，设置硬隔离并更新管线图纸。",
        "tags": ["触电", "电缆敷设", "管线探测"],
    },
    {
        "accident_case_id": "AC-MVP-030",
        "tenant_id": "CSCEC",
        "accident_type": "机械伤害",
        "severity": "一般事故",
        "project_type": "mep",
        "operation_scene": "冷水机组安装",
        "direct_cause": "机组搬运滚杠失控，操作人员手部被挤压。",
        "indirect_cause": "大件搬运方案缺失，指挥人员未持证上岗。",
        "involved_subjects": {"subjects": ["worker", "equipment"]},
        "warning_indicators": [{"metric_code": "HEAVY_LIFT_PLAN_MISSING", "value": 1}],
        "rectification_measures": "编制大件搬运方案，使用专用吊具替代滚杠人工推移。",
        "tags": ["机械伤害", "机电安装", "大件搬运"],
    },
    {
        "accident_case_id": "AC-MVP-031",
        "tenant_id": "CSCEC",
        "accident_type": "机械伤害",
        "severity": "险情",
        "project_type": "infrastructure",
        "operation_scene": "沥青拌合站运维",
        "direct_cause": "传送带清堵时未停机，清扫工具卷入传动部位。",
        "indirect_cause": "清堵作业未执行停机挂牌，培训不到位。",
        "involved_subjects": {"subjects": ["worker"]},
        "warning_indicators": [{"metric_code": "LOCKOUT_TAGOUT_VIOLATION", "value": 1}],
        "rectification_measures": "落实停机挂牌上锁，清堵工具加装防卷入挡板。",
        "tags": ["机械伤害", "拌合站", "挂牌上锁"],
    },
    {
        "accident_case_id": "AC-MVP-032",
        "tenant_id": "CSCEC",
        "accident_type": "机械伤害",
        "severity": "近失",
        "project_type": "housing",
        "operation_scene": "木工圆盘锯操作",
        "direct_cause": "锯片护罩被拆除，推送木料时险些伤手。",
        "indirect_cause": "违章改装设备，日常巡查未发现。",
        "involved_subjects": {"subjects": ["worker", "subcontractor"]},
        "warning_indicators": [{"metric_code": "EQUIPMENT_GUARD_REMOVED", "value": 1}],
        "rectification_measures": "恢复锯片护罩并清退违章改装设备，开展工具专项检查。",
        "tags": ["机械伤害", "圆盘锯", "防护罩"],
    },
    {
        "accident_case_id": "AC-MVP-033",
        "tenant_id": "CSCEC",
        "accident_type": "起重伤害",
        "severity": "一般事故",
        "project_type": "municipal",
        "operation_scene": "顶管机吊装下井",
        "direct_cause": "吊点选择不当导致设备倾斜，钢丝绳挤压作业人员。",
        "indirect_cause": "吊装方案未专家评审，现场指挥与信号工职责混淆。",
        "involved_subjects": {"subjects": ["equipment", "worker", "subcontractor"]},
        "warning_indicators": [{"metric_code": "LIFTING_PLAN_REVIEW_MISSING", "value": 1}],
        "rectification_measures": "重新计算吊点并专家论证，明确指挥与信号工分工。",
        "tags": ["起重伤害", "顶管施工", "吊装方案"],
    },
    {
        "accident_case_id": "AC-MVP-034",
        "tenant_id": "CSCEC",
        "accident_type": "起重伤害",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "物料提升机卸料平台",
        "direct_cause": "料台超载报警被屏蔽，平台轻微变形。",
        "indirect_cause": "设备维保弄虚作假，平台限载标识缺失。",
        "involved_subjects": {"subjects": ["equipment", "subcontractor"]},
        "warning_indicators": [{"metric_code": "EQUIPMENT_OVERLOAD_ALARM_BYPASS", "value": 1}],
        "rectification_measures": "恢复超载限位，重新标定料台并张贴限载牌。",
        "tags": ["起重伤害", "物料提升机", "超载"],
    },
    {
        "accident_case_id": "AC-MVP-035",
        "tenant_id": "CSCEC",
        "accident_type": "起重伤害",
        "severity": "近失",
        "project_type": "infrastructure",
        "operation_scene": "钢箱梁顶推施工",
        "direct_cause": "千斤顶行程不同步，梁体偏移险些倾覆。",
        "indirect_cause": "顶推监测系统未联网，操作不同步。",
        "involved_subjects": {"subjects": ["project", "equipment"]},
        "warning_indicators": [{"metric_code": "STRUCTURE_MONITOR_ALERT", "value": 1}],
        "rectification_measures": "同步校准千斤顶行程并接入位移监测预警。",
        "tags": ["起重伤害", "顶推施工", "结构监测"],
    },
    {
        "accident_case_id": "AC-MVP-036",
        "tenant_id": "CSCEC",
        "accident_type": "坍塌",
        "severity": "一般事故",
        "project_type": "mep",
        "operation_scene": "地下室电缆沟支护",
        "direct_cause": "沟槽边坡未按方案放坡，局部坍塌掩埋电缆。",
        "indirect_cause": "沟槽开挖方案未审批，雨后检查缺失。",
        "involved_subjects": {"subjects": ["project", "subcontractor"]},
        "warning_indicators": [{"metric_code": "TRENCH_SUPPORT_MISSING", "value": 1}],
        "rectification_measures": "按方案放坡并设置钢板桩支护，雨后复工前验收。",
        "tags": ["坍塌", "电缆沟", "沟槽支护"],
    },
    {
        "accident_case_id": "AC-MVP-037",
        "tenant_id": "CSCEC",
        "accident_type": "坍塌",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "地下室肥槽回填",
        "direct_cause": "回填土未分层夯实，挡土墙后土压力增大变形。",
        "indirect_cause": "回填质量验收不严，监测点布置不足。",
        "involved_subjects": {"subjects": ["project"]},
        "warning_indicators": [{"metric_code": "BACKFILL_COMPACTION_FAIL", "value": 1}],
        "rectification_measures": "拆除不合格回填层重新分层夯实，加密挡土墙位移监测。",
        "tags": ["坍塌", "回填施工", "挡土墙"],
    },
    {
        "accident_case_id": "AC-MVP-038",
        "tenant_id": "CSCEC",
        "accident_type": "坍塌",
        "severity": "近失",
        "project_type": "municipal",
        "operation_scene": "顶管工作井",
        "direct_cause": "工作井支护渗漏水，井壁局部剥落。",
        "indirect_cause": "井壁止水措施失效，地下水位上升未预警。",
        "involved_subjects": {"subjects": ["project", "worker"]},
        "warning_indicators": [{"metric_code": "GROUNDWATER_LEVEL_HIGH", "value": 1}],
        "rectification_measures": "补强止水帷幕并安装井内水位监测报警。",
        "tags": ["坍塌", "工作井", "地下水"],
    },
    {
        "accident_case_id": "AC-MVP-039",
        "tenant_id": "CSCEC",
        "accident_type": "高处坠落",
        "severity": "险情",
        "project_type": "municipal",
        "operation_scene": "高架桥防撞护栏施工",
        "direct_cause": "防撞墙外侧作业未设置生命线，人员失足被安全绳拉住。",
        "indirect_cause": "桥梁外侧作业方案缺失，生命线锚点验收不严。",
        "involved_subjects": {"subjects": ["worker"]},
        "warning_indicators": [{"metric_code": "LIFELINE_ANCHOR_FAIL", "value": 1}],
        "rectification_measures": "增设合格生命线锚点并开展桥梁外侧专项交底。",
        "tags": ["高处坠落", "桥梁施工", "生命线"],
    },
    {
        "accident_case_id": "AC-MVP-040",
        "tenant_id": "CSCEC",
        "accident_type": "物体打击",
        "severity": "一般事故",
        "project_type": "mep",
        "operation_scene": "屋面冷却塔组装",
        "direct_cause": "螺栓组件从屋面滑落，砸穿下方彩钢板防护。",
        "indirect_cause": "屋面物料未入箱，垂直运输未设防坠网。",
        "involved_subjects": {"subjects": ["worker", "subcontractor"]},
        "warning_indicators": [{"metric_code": "ROOF_MATERIAL_UNSECURED", "value": 3}],
        "rectification_measures": "物料入箱运输并设置防坠网，屋面下方扩大隔离区。",
        "tags": ["物体打击", "屋面施工", "防坠"],
    },
    {
        "accident_case_id": "AC-MVP-041",
        "tenant_id": "CSCEC",
        "accident_type": "触电",
        "severity": "险情",
        "project_type": "infrastructure",
        "operation_scene": "盾构机刀盘检修",
        "direct_cause": "刀盘驱动电机绝缘下降，检修时漏电保护动作。",
        "indirect_cause": "潮湿环境绝缘检测周期过长，检修票未复核。",
        "involved_subjects": {"subjects": ["equipment", "worker"]},
        "warning_indicators": [{"metric_code": "INSULATION_TEST_OVERDUE", "value": 1}],
        "rectification_measures": "恢复绝缘并缩短检测周期，潮湿环境强制二次验电。",
        "tags": ["触电", "盾构施工", "绝缘检测"],
    },
    {
        "accident_case_id": "AC-MVP-042",
        "tenant_id": "CSCEC",
        "accident_type": "机械伤害",
        "severity": "一般事故",
        "project_type": "municipal",
        "operation_scene": "顶管机主轴承更换",
        "direct_cause": "液压泵站软管爆裂，高压油喷射伤及周边设备受损。",
        "indirect_cause": "软管老化未更换，压力试验记录缺失。",
        "involved_subjects": {"subjects": ["equipment", "worker"]},
        "warning_indicators": [{"metric_code": "HYDRAULIC_HOSE_OVERDUE", "value": 1}],
        "rectification_measures": "更换软管并建立压力试验台账，设置液压隔离阀。",
        "tags": ["机械伤害", "液压系统", "顶管"],
    },
    {
        "accident_case_id": "AC-MVP-043",
        "tenant_id": "CSCEC",
        "accident_type": "起重伤害",
        "severity": "一般事故",
        "project_type": "mep",
        "operation_scene": "锅炉房设备吊装",
        "direct_cause": "汽车吊支腿未完全伸出，吊装中支腿下陷导致吊臂失稳。",
        "indirect_cause": "地基承载力未复核，吊装前未做试吊检查。",
        "involved_subjects": {"subjects": ["equipment", "subcontractor"]},
        "warning_indicators": [{"metric_code": "CRANE_OUTRIGGER_SETTLEMENT", "value": 1}],
        "rectification_measures": "铺设路基箱并复核地基，吊装前执行试吊和力矩复核。",
        "tags": ["起重伤害", "汽车吊", "支腿沉降"],
    },
    {
        "accident_case_id": "AC-MVP-044",
        "tenant_id": "CSCEC",
        "accident_type": "坍塌",
        "severity": "一般事故",
        "project_type": "infrastructure",
        "operation_scene": "隧道掌子面开挖",
        "direct_cause": "掌子面支护滞后，围岩掉块砸损设备。",
        "indirect_cause": "地质预报不准确，支护方案调整不及时。",
        "involved_subjects": {"subjects": ["project", "worker"]},
        "warning_indicators": [{"metric_code": "TUNNEL_SUPPORT_LAG_HOURS", "value": 6}],
        "rectification_measures": "加密地质预报并缩短支护循环，掉块区域增设超前支护。",
        "tags": ["坍塌", "隧道开挖", "超前支护"],
    },
    {
        "accident_case_id": "AC-MVP-045",
        "tenant_id": "CSCEC",
        "accident_type": "高处坠落",
        "severity": "近失",
        "project_type": "housing",
        "operation_scene": "外墙真石漆喷涂",
        "direct_cause": "吊绳磨损断裂前被发现，作业人员及时更换绳索。",
        "indirect_cause": "吊绳检查标准缺失，使用前检查未记录。",
        "involved_subjects": {"subjects": ["worker"]},
        "warning_indicators": [{"metric_code": "RIGGING_WEAR_ALERT", "value": 1}],
        "rectification_measures": "建立吊绳报废标准并执行使用前检查记录。",
        "tags": ["高处坠落", "外墙施工", "吊绳检查"],
    },
    {
        "accident_case_id": "AC-MVP-046",
        "tenant_id": "CSCEC",
        "accident_type": "物体打击",
        "severity": "险情",
        "project_type": "infrastructure",
        "operation_scene": "预制梁场堆场",
        "direct_cause": "梁体支撑垫木腐朽，梁体滑移撞击相邻梁端。",
        "indirect_cause": "堆场检查频次不足，垫木更换标准未执行。",
        "involved_subjects": {"subjects": ["equipment", "project"]},
        "warning_indicators": [{"metric_code": "YARD_SUPPORT_DEFECT", "value": 1}],
        "rectification_measures": "更换垫木并划分堆场限位，增加堆场日常巡检。",
        "tags": ["物体打击", "预制梁场", "堆场管理"],
    },
    {
        "accident_case_id": "AC-MVP-047",
        "tenant_id": "CSCEC",
        "accident_type": "触电",
        "severity": "一般事故",
        "project_type": "housing",
        "operation_scene": "户内精装修插座安装",
        "direct_cause": "未确认回路断电即拆线，作业人员触电。",
        "indirect_cause": "装修队伍未纳入统一临电管理，断电确认无签字。",
        "involved_subjects": {"subjects": ["worker", "subcontractor"]},
        "warning_indicators": [{"metric_code": "TEMP_ELECTRICITY_PERMIT_MISSING", "value": 1}],
        "rectification_measures": "装修队伍纳入临电管理，执行断电确认双人签字。",
        "tags": ["触电", "精装修", "临电管理"],
    },
    {
        "accident_case_id": "AC-MVP-048",
        "tenant_id": "CSCEC",
        "accident_type": "机械伤害",
        "severity": "险情",
        "project_type": "mep",
        "operation_scene": "风管法兰加工",
        "direct_cause": "剪板机脚踏开关失灵，设备异常启动被急停。",
        "indirect_cause": "设备日常点检未覆盖脚踏开关，急停按钮被遮挡。",
        "involved_subjects": {"subjects": ["worker", "equipment"]},
        "warning_indicators": [{"metric_code": "EMERGENCY_STOP_BLOCKED", "value": 1}],
        "rectification_measures": "修复脚踏开关并清理急停遮挡，纳入班前点检项。",
        "tags": ["机械伤害", "加工机械", "急停"],
    },
    {
        "accident_case_id": "AC-MVP-049",
        "tenant_id": "CSCEC",
        "accident_type": "起重伤害",
        "severity": "险情",
        "project_type": "housing",
        "operation_scene": "幕墙单元体吊装",
        "direct_cause": "单元体挂件焊缝开裂，吊装过程发出异响后停止。",
        "indirect_cause": "焊缝探伤比例不足，进场验收未抽检。",
        "involved_subjects": {"subjects": ["subcontractor", "equipment"]},
        "warning_indicators": [{"metric_code": "WELD_INSPECTION_FAIL", "value": 1}],
        "rectification_measures": "提高焊缝探伤比例，不合格批次全部退场复检。",
        "tags": ["起重伤害", "幕墙", "焊缝探伤"],
    },
    {
        "accident_case_id": "AC-MVP-050",
        "tenant_id": "CSCEC",
        "accident_type": "坍塌",
        "severity": "险情",
        "project_type": "mep",
        "operation_scene": "机房楼板预留洞口",
        "direct_cause": "楼板洞口盖板强度不足，堆料后盖板变形。",
        "indirect_cause": "洞口盖板未按设计承载验算，堆料管理失控。",
        "involved_subjects": {"subjects": ["project", "subcontractor"]},
        "warning_indicators": [{"metric_code": "FLOOR_OPENING_OVERLOAD", "value": 1}],
        "rectification_measures": "更换承载合格盖板并禁止洞口堆料，设置限载标识。",
        "tags": ["坍塌", "楼板洞口", "堆载管理"],
    },
]
