services:
  mysql:
    image: mysql:8.0
    container_name: cscec_safety_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-275874}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cscec_safety}
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
